export const tickets = [
  {
    id: 1,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 25,
  },
  {
    id: 2,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 25,
  },
  {
    id: 3,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: true,
    time: 25,
  },
  {
    id: 4,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 25,
  },
  {
    id: 5,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: true,
    time: 16,
  },
  {
    id: 6,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 13,
  },
  {
    id: 7,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 12,
  },
  {
    id: 8,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 9,
  },
  {
    id: 9,
    ticket: "B-95",
    service: "Юридическая лицо",
    status: false,
    time: 6,
  },
];